version: '2'
networks:
  app_net:
    driver: bridge
services:
  rabbitmq-server:
    image: rabbitmq:3-management-alpine
    networks:
      - app_net
    hostname: rabbitmq
    container_name: rabbitmq
    restart: always
   # environment:
    #  - RABBITMQ_DEFAULT_USER=user
    #  - RABBITMQ_DEFAULT_PASS=passwd
    #  - RABBITMQ_DEFAULT_VHOST=my_vhost
    volumes:
    - ./data/rabbitmq:/var/lib/rabbitmq
    ports:
    - "127.0.0.1:5672:5672"
  mysql:
    image: mysql:5.7
    networks:
      - app_net
    hostname: mysql
    container_name: mysql
    restart: always
    volumes:
    - ./data/mysql/data:/var/lib/mysql
    - ./data/mysql/conf:/etc/mysql/conf.d
    - ./data/mysql/logs:/opt/local/mysql/logs
    - ./data/mysql/binlog:/opt/local/mysql/binlog
    environment:
    - MYSQL_ROOT_PASSWORD=123456789
    ports:
    - "127.0.0.1:3306:3306"
  redis:
    image: redis:3-alpine
    networks:
      - app_net
    hostname: redis
    container_name: redis
    restart: always
    volumes:
    - ./data/redis/data:/data
    - ./data/redis/conf/redis.conf:/opt/local/redis/redis.conf
    ports:
    - "127.0.0.1:6379:6379"
    command:
    - "/opt/local/redis/redis.conf"
  eureka-1:
    image: jicki/eureka-cluster
    networks:
      - app_net
    hostname: eureka-1
    container_name: eureka-1
    restart: always
    environment:
    - EUREKA_SERVER_LIST=http://eureka-1:8761/eureka/
    ports:
    - 8761:8761
